### ISSUE TITLE
0.8.341 pre-release white box

### ISSUE THREAD

**Issue by InfoBlock** [BoiHanny/vrcosc-magicchatbox#23]
In the 0.8.341 pre-release there's an big white box at the bottom that doesn't go away
![image](https://github.com/BoiHanny/vrcosc-magicchatbox/assets/36295870/9071f346-1069-473c-a87d-a29aabf95bd4)

**Comment by BoiHanny** [comment]
@InfoBlock thx for reporting, ill look into it. There was a wing that we removed there (was always hidden)

**Comment by BoiHanny** [comment]
Please tell me if this issue is resolved in build `Pre-v0.8.350` that I just pushed,

**Comment by InfoBlock** [comment]
Looking good now!
![image](https://github.com/BoiHanny/vrcosc-magicchatbox/assets/36295870/ccc9ae16-4b5c-4b72-8774-0fbd3c03ff3f)

**Comment by BoiHanny** [comment]
Amazing, thx for letting me know!!!
![VRChat_2023-07-13_23-16-11 661_3840x2160_wrld_19c91eaa-37dd-4f8c-86de-5da83e8c976e](https://github.com/BoiHanny/vrcosc-magicchatbox/assets/114599052/6f069643-8f7f-4eba-ac8e-eaf35c05ce67)
