### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by lungrape** [BoiHanny/vrcosc-magicchatbox#25]
everything was fine up to a month ago when autoplay feature stopped working everytime my song changed it would say "paused" and wouldnt change unless i turned it off and back on, i never changed any settings since it was working but idk what to do now

**Comment by BoiHanny** [comment]
Hi,

I can't really reproduce this bug, can you explain... like step by step.
do you have these turned on?

![image](https://github.com/BoiHanny/vrcosc-magicchatbox/assets/114599052/ba2b20ac-f940-4533-9fd4-37e5f2d766d5)
