### ISSUE TITLE
Wine crashes on init

### ISSUE THREAD

**Issue by SpookySkeletons** [BoiHanny/vrcosc-magicchatbox#26]
The application calls an unimplemented win32 API dwrite call
dwritetextanalyzer_AnalyzeNumberSubstitution
which crashes due to it being a stub 
https://github.com/wine-mirror/wine/blob/de66ea9df6746917cada71d2c27b5cc38cbdd2f0/dlls/dwrite/analyzer.c#L1383

Is it possible this application may also be compiled for mono which is cross platform to avoid the win32 API hard dependency?

**Comment by BoiHanny** [comment]
Hey,

Thanks, I'm gonna look into it!

Boi
