### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by gobl1nk1ng** [BoiHanny/vrcosc-magicchatbox#28]
Would be nice to have the option to change the live background color of the display box.

**Comment by BoiHanny** [comment]
Can you explain more, do you mean the chatbox in vrchat or my application?

**Comment by gobl1nk1ng** [comment]
The Chatbox in vrchat.

**Comment by BoiHanny** [comment]
we can't control the color of the chatbox, we can only control the text
