### ISSUE TITLE
pre release bug

### ISSUE THREAD

**Issue by pearlharbor17** [BoiHanny/vrcosc-magicchatbox#33]
**Describe the bug**
when I try to download the pre release for version 0.8.321 it says object reference not set to an instance

**To Reproduce**
1. Go to magic chat box
2. Click on pre release in the bottom right
3. click on open log

**Expected behavior**
a text will pop up and say object not set to an instance

**Screenshots**
![image_2024-01-23_213037673](https://github.com/BoiHanny/vrcosc-magicchatbox/assets/157553251/a64e4a5c-c23f-4ee5-af12-c1006b239e36)

**Desktop (please complete the following information):**
 - OS: 64-bit operating system, x64-based processor
 - Browser opera gx
 - Version 22H2

**Comment by BoiHanny** [comment]
This should not happen anymore :P
