### ISSUE TITLE
MagicChatbox not sending enter

### ISSUE THREAD

**Issue by ImLvna** [BoiHanny/vrcosc-magicchatbox#40]
**Describe the bug**
In the preview, everything looks normal. In vrchat, the integrations are not seperated

**To Reproduce**
Basic Use

**Expected behavior**
![image](https://github.com/BoiHanny/vrcosc-magicchatbox/assets/44179559/9318e4e6-172a-4220-849f-0206c7f69191)

**Screenshots**
![image](https://github.com/BoiHanny/vrcosc-magicchatbox/assets/44179559/a87f8d1e-48fc-4df6-bc47-40837e46661d)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - MagicChatbox 0.8.757

**Comment by BoiHanny** [comment]
Yes, thank you for ur info <3 we are aware.
VRChat is tracking this issue: https://feedback.vrchat.com/open-beta/p/1400-v-no-longer-force-an-new-line-for-the-chatbox

**Comment by BoiHanny** [comment]
Vrchat reversed this change :)
