### ISSUE TITLE
Feature Request: More options for display of heart rate

### ISSUE THREAD

**Issue by navarr** [BoiHanny/vrcosc-magicchatbox#44]
Specifically for heart rate (as that's primarily what I use), but really for everything like this, it'd be nice if instead of having options that "do a or b" it could be split into options like "do a" "do b"

For example,

"Show BPM suffix instead of prefix icons"

I would actually love to show both.  I love the heart indicator, but I would love to also show the bpm after the number (as I've been asked "is that bpm?")

**Comment by BoiHanny** [comment]
![image](https://github.com/BoiHanny/vrcosc-magicchatbox/assets/114599052/bc18a124-500f-4725-ade2-529f4b1ad603)
I made some changes to the heartrate module, i hope this is what u requested :P
