### ISSUE TITLE
It doesn't open

### ISSUE THREAD

**Issue by UnguslyGrugged** [BoiHanny/vrcosc-magicchatbox#49]
Whenever I go to open magic chatbox it loads a little, stops, then closes the loading screen, doesn't open the app.

Not sure how anyone else can reproduce it, seems like a me, specific, issue

It opened and functioned just find when I first installed it, but it doesn't function properly.

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser: firefox
 - Version Magic chatbox-0.8.820

**Comment by BoiHanny** [comment]
Hello!!! can u show me a screenshot of the loading screen and where it stops?

**Comment by MythicalMaiden** [comment]
hey im having the same problem. this is what it looks like before it closes, thats how much itll load.
![Screenshot (42)](https://github.com/BoiHanny/vrcosc-magicchatbox/assets/166457752/bf44f9aa-397d-46dd-8988-2ab357729cdf)

**Comment by BoiHanny** [comment]
> hey im having the same problem. this is what it looks like before it closes, thats how much itll load. ![Screenshot (42)](https://private-user-images.githubusercontent.com/166457752/320678001-bf44f9aa-397d-46dd-8988-2ab357729cdf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2MjA2OTksIm5iZiI6MTcxMjYyMDM5OSwicGF0aCI6Ii8xNjY0NTc3NTIvMzIwNjc4MDAxLWJmNDRmOWFhLTM5N2QtNDZkZC04OTg4LTJhYjM1NzcyOWNkZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwOFQyMzUzMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YWU5ZjAxMWYzODNmYThlZmE1NzAwMWQxNDY1ZWJlZDFiYjM5NGNlNjVhZjA2MWEwNDBiZjU3OGRiNmY4NGM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.muNS8in9NOYORp52bnhIxUaP5R9KYE-4tdz1dC_wg1M)

Yeah this is a hard one, during this time it's loading the main setting module.
u can fix this one by deleting the: settings.xml from this folder: %appdata%/Vrcosc-MagicChatbox (just put this in ur file explorer)

**Comment by MythicalMaiden** [comment]
The thing is- I've never used mcb before so im unable to find that document

**Comment by BoiHanny** [comment]
Hellow I think this is fixed in one of the latest updates i brought out 📦 
https://github.com/BoiHanny/vrcosc-magicchatbox/releases/download/v0.8.885/MagicChatbox-0.8.885.zip
