### ISSUE TITLE
Wont show in vrchat

### ISSUE THREAD

**Issue by BillieBarbatos** [BoiHanny/vrcosc-magicchatbox#52]
the app is open dut wont show on vrchat

**Comment by GlydetheSurfer** [comment]
the same is happening to me, i stopped using it because of this.. and i can see that no one is even commenting. its like this application's support is now dead. it was working fine a few weeks ago, but now it just wont work in vrchat anymore.

**Comment by Lyrikidionisos** [comment]
Hi there, 

i am one of the Team-Members of this project. 
We mostly use our discord network to give proper support.

We offer clear support for problems intentionally on our discord server:

**https://discord.gg/svZE468dtM**

Please create a ticket there for all technical problems. We're happy to help.

Kind regards
_Ethan_
