### ISSUE TITLE
wont stay open 

### ISSUE THREAD

**Issue by GrandLizardman69** [BoiHanny/vrcosc-magicchatbox#54]
when ever i try to open the app it says loading status but then closes itself

**Comment by BoiHanny** [comment]
Hi which version r u using?

**Comment by GrandLizardman69** [comment]
> Hi which version r u using?

im not usre but i recently downloaded it

**Comment by BoiHanny** [comment]
Hallo! I believe this issue has been fixed in one of the recent updates that I released. 📦
https://github.com/BoiHanny/vrcosc-magicchatbox/releases/download/v0.8.885/MagicChatbox-0.8.885.zip
