### ISSUE TITLE
.NET 6 End of Life

### ISSUE THREAD

**Issue by jan-Sanku** [BoiHanny/vrcosc-magicchatbox#55]
.NET 6.0 will reach End of Life in a few months. It will no longer receive maintenance updates, which might eventually leave MagicChatbox in a vulnerable state. Please consider updating to .NET 8.0 before this point.

**Comment by BoiHanny** [comment]
Hey @LordVertice, that's a good one!

MCb also runs perfectly on .NET 8. However, many users don't have the .NET 8 version installed. Therefore, before upgrading, I need to inform the users about the upcoming changes. I would like to do that in MCb itself 📦

Thank u for letting me know!

**Comment by BoiHanny** [comment]
Hey @jan-Sanku,

We've just pushed [This pull](https://github.com/BoiHanny/vrcosc-magicchatbox/pull/71) to the public in version 0.9.010. This version is designed to check if you have .NET 8 installed; if not, it should give you the option to install it directly if needed.

We will soon be upgrading our codebase to .NET 8. We haven't encountered any problems from our side, and everything is working smoothly.
