### ISSUE TITLE
inconsistent playback data from windows media api

### ISSUE THREAD

**Issue by LordVertice** [BoiHanny/vrcosc-magicchatbox#56]
playback in firefox (works as intended)
![image](https://github.com/BoiHanny/vrcosc-magicchatbox/assets/56739341/c80d5f50-0ca6-4c40-9933-6b300e49c113)

foobar2000 (missing time)
![image](https://github.com/BoiHanny/vrcosc-magicchatbox/assets/56739341/a592b3bd-647b-4af6-80e8-23dc19ee6e15)

media player (shows as paused, no song name or artist, but time is shown)
![image](https://github.com/BoiHanny/vrcosc-magicchatbox/assets/56739341/a73f3e87-003e-4f93-a6a3-8cb92a3c0c47)

VLC and audacity don't work at all.

is this a bug in MagicChatbox, or an issue with the applications not providing the data properly? can this be fixed on your end?

**Comment by BoiHanny** [comment]
I've just released an update for the media player to address the issue where it appeared as paused while showing the time. 

https://github.com/BoiHanny/vrcosc-magicchatbox/releases/tag/v0.8.886

The interaction between some applications and the Windows Media API can be inconsistent. Some applications may only provide partial data, such as just the song title without the artist, or just the playback time. Unfortunately, if the data isn't available from the application, there's nothing we can do to retrieve it.

**Comment by Mirohslav** [comment]
Hi, i have the same issue, i play through chrome i didnt had problem before but i got new pc and downloaded and everything works except the media player and its paused even though its playing i tried the link above didnt work and updated to latest and still same. :((
