### ISSUE TITLE
App won't stay open

### ISSUE THREAD

**Issue by SophiaGamble** [BoiHanny/vrcosc-magicchatbox#57]
Whenever i try to open the app it will load and say please stay put and then so on then it just closes itself  and i have the recent and up to date version

**Comment by pokeboo** [comment]
i am having the same issue the download stops  after like 5 seconds i was able to download version 0.8.321

**Comment by Lyrikidionisos** [comment]
Hello @pokeboo @SophiaGamble ,

i apologize for the late response.

The latest preleases have fixed issues of the chatbox having trouble opening.
Also the new github start page have new instructions and dependencies noted.

Please follow the steps shown.

For further and faster support please join the discord network:
[MagicChatbox Support Discord](https://discord.gg/MagicChatbox)

Thanks 
~ Ethan
