### ISSUE TITLE
No file

### ISSUE THREAD

**Issue by FeeFeeee** [BoiHanny/vrcosc-magicchatbox#69]
**Describe the bug**
im not some nood when it comes to pc's so im not sure if im just skipping steps or being stupid, but the part where it says to run 'magicchatbox.exe' i dont have that file when installing this, i have 'magicchatbox.sln' and a bunch of random CS files and also have 'magicchatboxV2' but when try opening NET just opens up with repair, uninstall or modify, please help out if you could <3
**To Reproduce**
1. Go to 'C:\Users\....\Desktop\vrcosc-magicchatbox-master'
2. Click on 'magicchatboxV2'
3. Scroll down to 'MagicChatboxV2'
4. See error... NET opens up as stated above with uninstall/moify etc like python does sometimes

**Expected behavior**
i havent gotten round to using this so im not sure what should open but im sure its just the chatbox
**Screenshots**
![image](https://github.com/user-attachments/assets/bbae5c8e-09a4-44a9-b4b5-4a72b7ace5e1)

**Desktop (please complete the following information):**
 - OS: windows 11
 - Browser chrome
 

**Additional context**

**Comment by BoiHanny** [comment]
Hey @FeeFeeee! Welcome! 
I see you've downloaded the source code. To run it, you'll need to use Visual Studio. If you're only interested in running MagicChatbox without examining the code, you can simply click on [this link](https://github.com/BoiHanny/vrcosc-magicchatbox/releases/download/v0.9.010/MagicChatbox-0.9.010.zip) to download the application's files.
