### ISSUE TITLE
My Chat box isn't appearing 

### ISSUE THREAD

**Issue by SophiaGamble** [BoiHanny/vrcosc-magicchatbox#74]
Whenever i open MagicChatBox immediately the chat box would appear but today it has just stopped appearing and ive tried closing it and reclosing it i've tried changing the ip address and then changing it back and ive tried restarting my computer it just won't appear at all

**Comment by SophiaGamble** [comment]
one of my settings was messed up lol

**Comment by SigmaSigmaMirror** [comment]
What was the setting?
