### ISSUE TITLE
Got Banned two days after using this tool

### ISSUE THREAD

**Issue by Gxinz** [BoiHanny/vrcosc-magicchatbox#90]
Hello,

Today I just received a mail from vrchat that I got banned due to client modifications... I just installed this tool, connected everything and we're able to play. Two days later I received my ban...

**Comment by BoiHanny** [comment]
Hi Gxinz,

I'm sorry to hear about the ban you received from VRChat.

I want to assure you that MagicChatbox does not modify the VRChat client in any way. Our tool solely utilizes the OSC (Open Sound Control) endpoint VRChat provides for its functionality. This approach is fully compliant with VRChat's guidelines.

For your reference, here's an overview of OSC as documented by VRChat: [OSC Overview](https://docs.vrchat.com/docs/osc-overview).

Additionally, I checked with the official VRChat Discord server, and the VRChat team confirmed that using the OSC endpoint in this manner does not violate the Terms of Service.

![image](https://github.com/user-attachments/assets/77e72458-927e-4118-a22c-948bfabba4a5)

Other modifications or third-party tools might have contributed to the ban. I recommend reviewing any other software or plugins you might have installed alongside MagicChatbox. If you believe the ban was a mistake and you've only been using MagicChatbox without any other client modifications, I strongly encourage you to reach out to VRChat Support to appeal the ban.

I wish you luck!

**Comment by Gxinz** [comment]
Okay thats good to hear. Im already applied for a ban appeal. I want to know what happened, I hope they can help me.
